version: '3.4'

services:
  tictactoe:
    image: ${DOCKER_REGISTRY-}tictactoe
    build:
      context: .
      dockerfile: /Dockerfile

  webui:
    image: ${DOCKER_REGISTRY-}npmt
    build:
      context: .
      dockerfile: src\webui/Dockerfile